### ISSUE TITLE
Android crashes: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by Elijen** [expo/turtle#74] opened 2019-05-31 19:31 UTC
I hope this is the correct place to create the issue since it seems to be caused by some changes in the way standalone apps are built using `expo build:android`.

We are detecting crashes on multiple devices: 
![Screen Shot 2019-05-31 at 21 26 14](https://user-images.githubusercontent.com/1304054/58729851-c3148a80-83ea-11e9-9fdf-5765b0bd34e3.png)

The error:
```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
<anonymous>
```

Backtrace is almost empty:
![Screen Shot 2019-05-31 at 19 51 50](https://user-images.githubusercontent.com/1304054/58729747-86489380-83ea-11e9-8776-ed31eb8871bd.png)

The interesting part is: 
- standalone build that was built March 5th and is using the same Expo SDK version and very similar code works fine
- when the app was opened via older Expo client app it worked
- the app again crashes when opened in the latest Expo client app (v33)

This makes me think that the issue is caused by a build option that was added in the last few weeks.

```
Expo CLI 2.18.7 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      Yarn: 1.13.0 - ~/.nvm/versions/node/v8.15.1/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.10 => 32.0.10 
      @types/react: ^16.4.14 => 16.8.10 
      @types/react-native: ^0.57.43 => 0.57.43 
      @types/react-navigation: ^3.0.6 => 3.0.6 
      expo: ^32.0.5 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.8.1 => 3.8.1 
    npmGlobalPackages:
      expo-cli: 2.18.7
```

**Comment by Elijen** [comment] 2019-06-03 06:46
I think this could be related to https://github.com/facebook/react-native/issues/24261 although that issue seems to be related to 64bit builds which Expo does not support yet.

**Comment by wkozyra95** [comment] 2019-06-04 13:12
How often those crashes happen on the client and in the standalone build? Do you know how to reproduce them reliably?
Most likely crashes as caused by bug in jsc (vm for javascript).

The version from sdk-33 bundled in react-native@0.59 was cached in build directory and when we released fix for sdk-32 it was bundled instead old version.
For sdk 32 standalone builds fix should be deployed soon, the client is more problematic because this is a version that contains fixes required to make 64-bit builds possible.

**Comment by Elijen** [comment] 2019-06-04 13:24
I have an app that crashes 100% times when navigating into a certain view, but I wasn't able to figure out what causes the issue exactly. There are quite a lot of complex views on the screen. Removing some borderRadius styles seemed to help a little (app crashes few taps later), but not to the point I'd be convinced it's caused by that.

I don't understand the second part of your comment very much. Are you saying that the sdk32 in Expo client app was broken by accident (cached build)? If the Expo client app is fixed before standalone builds we could tell customers to use it as a workaround until we update our app.

If the 64-bit builds are the problem I think there are some workarounds mentioned in the issue I linked: facebook/react-native#24261, but I guess you guys are already aware.

**Comment by wkozyra95** [comment] 2019-06-04 13:57
Yes, we updated sdk-32 by accident with jsc used in react-native@0.59.
Sdk32 build will be fixed first, so you need to just rebuild app when it's ready.

For client we have 2 options
- downgrading version jsc to the one used previously (might not work with new react-native in sdk33)
- upgrading to newest jsc (it was just released, so it's a bit risky and might be less stable)

**Comment by wkozyra95** [comment] 2019-06-06 14:50
fixes for sdk32 sdk33 and client are released

**Closed by wkozyra95** 2019-06-06 14:50 UTC

**Comment by Elijen** [comment] 2019-06-09 12:06
Thank you, I can confirm that rebuilding the app fixed the issue.
